### ISSUE TITLE
Write three scenarios for the project.

### ISSUE THREAD

**Issue by adilaghayev** [batidibek/SWE_574_Group_2#11]
Write three different usage scenarios for the project that includes:

– The user and their persona (role)
– Preconditions – if any (such as: the user that has already logged in).
– Specific actions to achieve a desired goal (what the user wants to do). Describe each
step until the scenario is completed. Steps must be enumerated.
– Acceptance criteria (the conditions that describe a successful outcome for the action)
**Important note**: Your user scenarios must be based on realistic user and content. Do
not use sign up or login as scenarios.

https://piazza.com/class_profile/get_resource/k5z8641lgkatg/k70njrn6baq5o4

**Comment by batidibek** [comment]
Scenario 1 done

**Comment by adilaghayev** [comment]
Scenario 3 done
