### ISSUE TITLE
Post Types: "Create Post Type" Function

### ISSUE THREAD

**Issue by batidibek** [batidibek/SWE_574_Group_2#39]

**Comment by merveminadursun** [comment]
Community altında Post Type yaratabiliyoruz. Şu an sadece DB'de gözüküyor. Frontende getirmedim.

**Comment by merveminadursun** [comment]
generic post type'ları yaratıyorum

**Comment by merveminadursun** [comment]
community'nin post typeları artık listelenebiliyor
