### ISSUE TITLE
Software requirement elicitation

### ISSUE THREAD

**Issue by adilaghayev** [batidibek/SWE_574_Group_2#5]
Prepare a functional and non-functional requirements document draft.

**Comment by merveminadursun** [comment]
I identified product requirements about "data types" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page.

**Comment by merveminadursun** [comment]
I identified product requirements about "posts" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page.

**Comment by merveminadursun** [comment]
I identified product requirements about "comments" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page.

**Comment by merveminadursun** [comment]
I identified product requirements about "semantic tags and search" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page.

**Comment by adilaghayev** [comment]
I identified product requirements about "Inapproperiate Post Flagging" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements#inappropriate-post-flagging) page.

**Comment by adilaghayev** [comment]
I identified product requirements about "Subscription" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements#subscription) page.

**Comment by adilaghayev** [comment]
I identified product requirements about "Notifications" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements#notification) page.

**Comment by batidibek** [comment]
"Semantic Search" and "Add Information to Posts" features also added on Requirements document.
