### ISSUE TITLE
Prepare a list of questions for unclear requirements.

### ISSUE THREAD

**Issue by adilaghayev** [batidibek/SWE_574_Group_2#6]
Prepare a list of questions for the requirements that need clarification.

**Comment by merveminadursun** [comment]
I identified product requirements about "data types" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page.

**Comment by merveminadursun** [comment]
I identified product requirements about "posts" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page

**Comment by merveminadursun** [comment]
I identified product requirements about "comments" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page

**Comment by merveminadursun** [comment]
I identified product requirements about "semantic tags and search" and documented them on [Requirements](https://github.com/batidibek/SWE_574_Group_2/wiki/Requirements) page

**Comment by adilaghayev** [comment]
- Inappropriate Post Flagging - community driven or automatic?
- Audio Support - for accessibility or as a posting feature?
- Summary - summary of available data across post types and communities or summary of individual posts?
