### ISSUE TITLE
Create a meeting report for the meeting on 24.02.2020

### ISSUE THREAD

**Issue by burcuozkanat** [batidibek/SWE_574_Group_2#7]

**Comment by merveminadursun** [comment]
- Meeting agenda has been set on 20.02.2020
- Attendees' availability have been checked before meeting on 20.02.2020
- Notes have been taken during the meeting on 20.02.2020
- Meeting report has been wrote down on wiki. Refer: [Meeting 2](https://github.com/batidibek/SWE_574_Group_2/wiki/Meeting-%232-20.02.2020)
