### ISSUE TITLE
Adding Tag: When changing the tags input box, Get Tag Suggestions button does not work

### ISSUE THREAD

**Issue by merveminadursun** [batidibek/SWE_574_Group_2#75]
Test case:

1. Click on the "NEW COMMUNITY" button
2. Write down "metallica" in "Tags" input box.
3. Click on the Get Tag Suggestions button 
4. Write down "metallica" and enter, then write down "iron maiden" and enter in "Tags" input box.
5. Click on the Get Tag Suggestions button, it does not work.

I expect tag suggestions both for metallica and iron maiden but nothing happened.

Once you get tag suggestions, it is not possible to reselect another tag topic.

**Comment by batidibek** [comment]
solved
