### ISSUE TITLE
Inappropriate Post Flagging - community driven or automatic?

### ISSUE THREAD

**Issue by adilaghayev** [batidibek/SWE_574_Group_2#8]
Follow up on Issue #6

Clarify the requirement for post flagging. Is it community driven or automatic?

**Comment by batidibek** [comment]
It will be community driven. Users shall add flags for  inappropriate posts.

**Comment by adilaghayev** [comment]
If a post reaches a certain threshold of flags, the post should be sent to the community owner group for manual inspection.
